# Generated by Django 4.2.20 on 2025-05-01 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0, verbose_name='Puntos')),
                ('rebotes', models.IntegerField(default=0, verbose_name='Rebotes')),
                ('asistencias', models.IntegerField(default=0, verbose_name='Asistencias')),
                ('robos', models.IntegerField(default=0, verbose_name='Robos')),
                ('tapones', models.IntegerField(default=0, verbose_name='Tapones')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Jugador')),
                ('equipo', models.CharField(default='Unknown', max_length=50, verbose_name='Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_premio', models.CharField(max_length=100, verbose_name='Nombre del Premio')),
                ('año', models.CharField(default='Unknown', max_length=20, verbose_name='Año')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='main.jugador', verbose_name='Jugador')),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='director',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='generos',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='pais',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.AddField(
            model_name='estadistica',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='main.jugador', verbose_name='Jugador'),
        ),
    ]
