# Generated by Django 4.2.20 on 2025-05-01 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_estadistica_jugador_premio_remove_pelicula_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='asistencias',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jugador'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='puntos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='rebotes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='robos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='tapones',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='premio',
            name='año',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='premio',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jugador'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='nombre_premio',
            field=models.CharField(max_length=100),
        ),
    ]
