# Generated by Django 4.2.20 on 2025-05-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_estadistica_asistencias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premio',
            options={'ordering': ['-año']},
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='main.jugador'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='año',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='premio',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='main.jugador'),
        ),
        migrations.AlterUniqueTogether(
            name='premio',
            unique_together={('nombre_premio', 'año', 'jugador')},
        ),
    ]
