# Generated by Django 4.2.20 on 2025-05-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_premio_options_alter_estadistica_jugador_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='premio',
            unique_together=set(),
        ),
    ]
