# Generated by Django 4.2.20 on 2025-05-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_premio_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='premio',
            unique_together={('jugador', 'nombre_premio', 'año')},
        ),
    ]
